---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
      - name: static-website
        image: static:0.1.0
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: static-load-balancer
spec:
  selector:
    app: static-website
  ports:
    - port: 80  #00
      targetPort: 80
  type: LoadBalancer

